# Generated by Django 5.1 on 2024-08-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('legal', 'LEGAL'), ('individual', 'INDIVIDUAL')], default='individual', max_length=10, verbose_name='user type'),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
