# Generated by Django 5.1 on 2024-08-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productattribute_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(help_text='in liters', verbose_name='size'),
        ),
    ]
