# Generated by Django 5.1 on 2024-08-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productattribute_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='size',
        ),
    ]
