# Generated by Django 5.1 on 2024-08-20 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='all_media_files/', validators=[django.core.validators.FileExtensionValidator(['jpn', 'jpeg', 'png', 'mp4', 'mp3'])], verbose_name='file')),
                ('type', models.CharField(choices=[('image', 'Image'), ('vidio', 'Vidio'), ('audio', 'Audio'), ('other', 'Other')], default='image', max_length=28, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
            },
        ),
    ]
