# Generated by Django 5.1 on 2024-08-20 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='vidio',
            new_name='video',
        ),
    ]
