# Generated by Django 5.1 on 2024-08-24 11:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_aboutusgallery_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='phone_number1'),
        ),
    ]
